"""Beam synthesis — merge surviving research directions into a coherent report.

Unlike sequential concatenation, this synthesizer cross-references evidence
across directions, identifies agreements/disagreements, and weaves findings
into a unified narrative.
"""

from __future__ import annotations

from typing import List

import structlog

from deep_research.config import DEFAULT_MODEL
from deep_research.tools.llm_caller import LLMCaller
from deep_research.tools.source_extractor import (
    SourceExtraction,
    format_extractions_as_evidence,
)

from .hypothesis_generator import ResearchDirection

log = structlog.get_logger()


# ── Synthesis prompt ─────────────────────────────────────────────────────────

_SYNTHESIS_PROMPT = """Write a comprehensive research report synthesising findings from multiple research directions that were investigated in parallel.

Research Query: {query}

Research Directions Investigated:
{directions_text}

Source Evidence:
{evidence}

Requirements:
- Start with # Title (a descriptive title for the report)
- Include ## Abstract (200-300 words summarising the key findings)
- Organise into logical ## sections that integrate findings across directions
- DO NOT present directions sequentially — synthesise and cross-reference them
- Highlight areas where directions agree, and where they disagree or offer complementary insights
- Use inline citations [1], [2], etc. corresponding to the numbered sources
- Include specific data points, statistics, and quotes from sources
- End with ## Conclusion that ties together the most important findings
- End with ## References listing all cited sources
- Aim for 2000-4000 words
- Be analytical and balanced — interpret evidence, don't just summarise it
- Acknowledge limitations and gaps in the evidence

Important: This report was generated by exploring {n_directions_total} candidate research directions, of which {n_surviving} were selected as most promising after evidence-based scoring. The surviving directions are presented above."""


# ── Synthesis function ───────────────────────────────────────────────────────


async def synthesize_beams(
    llm: LLMCaller,
    surviving_directions: List[ResearchDirection],
    all_extractions: List[SourceExtraction],
    query: str,
    n_directions_total: int = 6,
) -> str:
    """Merge surviving research directions into a final markdown report.

    Args:
        llm: LLM caller instance.
        surviving_directions: Directions that survived beam selection.
        all_extractions: Deduplicated extractions from all surviving directions.
        query: The original research query.
        n_directions_total: Total number of initial hypotheses (for context).

    Returns:
        Markdown report text.
    """
    # Build directions summary
    directions_text = ""
    for d in surviving_directions:
        directions_text += (
            f"\n### Direction: {d.thesis}\n"
            f"Angle: {d.angle}\n"
            f"Promise Score: {d.promise_score:.1f}/10\n"
            f"Evidence Quality: {d.evidence_quality_score:.1f}/10\n"
            f"Sources: {len(d.extractions)} extractions\n"
            f"\nDetailed Analysis:\n{d.detailed_analysis}\n"
        )

    # Format evidence
    evidence = format_extractions_as_evidence(all_extractions)

    prompt = _SYNTHESIS_PROMPT.format(
        query=query,
        directions_text=directions_text,
        evidence=evidence,
        n_directions_total=n_directions_total,
        n_surviving=len(surviving_directions),
    )

    log.info(
        "synthesis_start",
        query=query[:60],
        n_directions=len(surviving_directions),
        n_extractions=len(all_extractions),
        prompt_chars=len(prompt),
    )

    try:
        report_md = await llm.complete(
            prompt,
            model=DEFAULT_MODEL,
            max_tokens=8192,
            temperature=0.3,
        )
    except Exception as exc:
        log.error("synthesis_failed", error=str(exc))
        # Fallback: concatenate direction analyses
        report_md = _fallback_report(
            query, surviving_directions, all_extractions
        )

    log.info(
        "synthesis_done",
        report_chars=len(report_md),
        report_words=len(report_md.split()),
    )
    return report_md


def _fallback_report(
    query: str,
    directions: List[ResearchDirection],
    extractions: List[SourceExtraction],
) -> str:
    """Build a minimal report from direction analyses when synthesis fails."""
    parts = [
        f"# Research Report: {query}\n",
        "## Abstract\n",
        f"This report investigates the query by exploring {len(directions)} "
        f"research directions, drawing on {len(extractions)} sources.\n",
    ]

    for d in directions:
        parts.append(f"\n## {d.angle.title()}: {d.thesis}\n")
        if d.detailed_analysis:
            parts.append(d.detailed_analysis)
        else:
            summaries = [e.summary for e in d.extractions if e.summary]
            parts.append("\n\n".join(summaries[:8]))
        parts.append("\n")

    parts.append("\n## References\n")
    for i, e in enumerate(extractions, 1):
        parts.append(f"[{i}] {e.title} — {e.url}\n")

    return "\n".join(parts)
